In [17]:
import numpy as np 
import pandas as pd 

def count_reps(count):
    count = count.dropna()
    count = count.to_numpy()
    count -= np.mean(count)
    t = (np.where(count > 0, 0, 1))
    b = t[1:] - t[:-1]
    return np.sum(b[b==1])

def count_reps_2(tens):
    tens -= np.mean(tens, axis=0)
    t = (np.where(tens > 0, 0, 1))
    b = t[1:] - t[:-1]
    b = b[np.any(b, 1)]
    b[b==-1] = 0
    return np.sum(b, axis=0)

In [18]:
from new_data_loader import bench, squat, deadlift

ValueError: No objects to concatenate

In [3]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import numpy as np

df = deadlift[-1]

def analyze_centered_signals(rep_df, title): 
    fig = go.Figure()
    print(rep_df[['gravityX', 'gravityY', 'gravityZ']])
    a = rep_df['gravityX']
    a -= np.mean(a)
    
    b = rep_df['gravityY'] 
    b -= np.mean(b)
    
    c = rep_df['gravityZ'] 
    c -= np.mean(c)
    
    fig.add_trace(
        go.Scatter(x=list(range(len(a))), y=a, name="gravityX")
    )
    fig.add_trace(
        go.Scatter(x=list(range(len(b))), y=b, name="gravityY")
    )
    fig.add_trace(
        go.Scatter(x=list(range(len(c))), y=c, name="gravityZ")
    )
    
    fig.update_layout(
        height=600, 
        title="Gravity Signals Over Time",
        xaxis_title="Time Steps",
        yaxis_title=title,
        hovermode="x unified", 
        legend=dict(
            title="Legend",  
            x=1,  
            y=1,  
            bordercolor="Black",  
            borderwidth=1  
        )
    )
    
    fig.show()
    
    print(count_reps(a), count_reps(b), count_reps(c))


NameError: name 'deadlift' is not defined

In [4]:
analyze_centered_signals(squat[-1], "centered gravity signals")

NameError: name 'analyze_centered_signals' is not defined

In [5]:
analyze_centered_signals(squat[2], "centered gravity signals")

NameError: name 'analyze_centered_signals' is not defined

In [6]:
analyze_centered_signals(squat[2], "centered gravity signals")

NameError: name 'analyze_centered_signals' is not defined

In [7]:
#keep in mind datatype 
#

In [8]:
np.nan_to_num(squat[-1][['gravityX', 'gravityY', 'gravityZ']].to_numpy(), 0)

NameError: name 'squat' is not defined

In [9]:
(squat[-1][['gravityX', 'gravityY', 'gravityZ']]).dropna()

NameError: name 'squat' is not defined

In [10]:
np.nan_to_num(squat[-1][['gravityX', 'gravityY', 'gravityZ']].to_numpy(), 0)

NameError: name 'squat' is not defined

In [11]:
np.average(np.nan_to_num(squat[-1][['gravityX', 'gravityY', 'gravityZ']].to_numpy(), 0))

NameError: name 'squat' is not defined

In [12]:
np.mean((squat[-1][['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy(), axis=0)

NameError: name 'squat' is not defined

In [13]:
tens = (squat[-1][['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy()
tens

NameError: name 'squat' is not defined

In [14]:
tens.shape

NameError: name 'tens' is not defined

In [89]:
count_reps_2(tens)

array([6, 1, 4])

In [90]:
np.average(tens, axis=0)

array([1.81408991e-18, 5.80508771e-18, 0.00000000e+00])

In [91]:
np.average(tens[:, 0])

1.8140899095182297e-18

In [92]:
tens = (squat[-1][['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy()
tens -= np.mean(tens, axis=0)
t = (np.where(tens > 0, 0, 1))
b = t[1:] - t[:-1]
b = b[np.any(b, 1)]

In [93]:
b

array([[ 1,  1,  0],
       [ 0,  0,  1],
       [-1,  0,  0],
       [ 1,  0,  0],
       [ 0,  0, -1],
       [ 0,  0,  1],
       [ 0,  0, -1],
       [ 0,  0,  1],
       [-1,  0,  0],
       [ 1,  0,  0],
       [-1,  0,  0],
       [ 1,  0,  0],
       [-1,  0,  0],
       [ 1,  0,  0],
       [-1,  0,  0],
       [ 1,  0,  0],
       [ 0,  0, -1],
       [ 0,  0,  1]])

In [94]:

b[b==-1] = 0

In [95]:
b

array([[1, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 1]])

In [96]:
#b[np.any(b, 1)]

In [97]:
np.sum(b, axis=0)

array([6, 1, 4])

In [98]:
count_reps_2(tens)

array([6, 1, 4])

In [99]:
tens = (squat[-1][['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy()
tens -= np.mean(tens, axis=0)
t = (np.where(tens > 0, 0, 1))
b = t[1:] - t[:-1]
b = b[np.any(b, 1)]
b[b==-1] = 0
np.sum(b, axis=0)

array([6, 1, 4])

In [100]:
count_reps_2(tens)

array([6, 1, 4])