In [2]:
import numpy as np 
import pandas as pd 
import time 
from numpy_models import count_reps, count_reps_2
from data_loader import bench, squat, deadlift
from tqdm import tqdm

neal deadlift 0
brian deadlift 0
brian bench 0
tejas bench 0
novel bench 0
neal bench 0
brian bench 1
brian bench 2
tejas bench 1
novel bench 1
novel bench 2
brian bench 3
tejas bench 2
brian bench 4
tejas bench 3
neal bench 1
brian bench 5
novel bench 3
brian bench 6
brian squat 0
novel squat 0
brian squat 1
brian squat 2
tejas squat 0
novel squat 1
brian squat 3
novel squat 2
novel squat 3
neal squat 0
brian squat 4
{'bench': {'brian': 7, 'novel': 4, 'tejas': 4, 'neal': 2}, 'squat': {'brian': 5, 'novel': 4, 'tejas': 1, 'neal': 1}, 'deadlift': {'brian': 1, 'novel': 0, 'tejas': 0, 'neal': 1}}
                           relativeAltitude  seconds_elapsed    pressure  \
name  workout  set_number                                                  
brian bench    0                       0.00         7.011909  100.453018   
               0                       0.00         7.867835  100.453293   
               0                      -0.03        10.968242  100.454849   
               0    

ModuleNotFoundError: No module named 'tqdm'

In [2]:
bench_out, squat_out, deadlift_out = [], [], []
start_time = time.time()
for e in tqdm(bench):
    bench_out.append([count_reps(e['gravityX']), count_reps(e['gravityY']), count_reps(e['gravityZ'])])

for e in tqdm(squat):
    squat_out.append([count_reps(e['gravityX']), count_reps(e['gravityY']), count_reps(e['gravityZ'])])

for e in tqdm(deadlift):
    deadlift_out.append([count_reps(e['gravityX']), count_reps(e['gravityY']), count_reps(e['gravityZ'])])
time_f = time.time() - start_time
print(time_f/(len(squat) + len(bench) + len(deadlift)))

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 1194.79it/s]

0.0017336289087931315


In [3]:
bench_out_2, squat_out_2, deadlift_out_2 = [], [], []
start_time = time.time()
for e in tqdm(bench):
    tens = (e[['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy()
    bench_out_2.append(count_reps_2(tens))

for e in tqdm(squat):
    tens = (e[['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy()
    squat_out_2.append(count_reps_2(tens))
    
for e in tqdm(deadlift):
    tens = (e[['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy()
    deadlift_out_2.append(count_reps_2(tens))

time_f = time.time() - start_time
print(time_f/(len(squat) + len(bench) + len(deadlift)))

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 907.47it/s]

0.0013706684112548828


In [4]:
np.array(bench_out_2).shape

(17, 3)

In [5]:
np.array(bench_out).shape

(17, 3)

In [6]:
#check correctness 
np.equal(bench_out_2, bench_out).all(), np.equal(squat_out_2, squat_out).all(), np.equal(deadlift_out_2, deadlift_out).all(),

(np.True_, np.True_, np.True_)

In [7]:
bench_out, squat_out, deadlift_out = [], [], []
bench_out_2, squat_out_2, deadlift_out_2 = [], [], []
def m1():
    start_time = time.time()
    for e in (bench):
        bench_out.append([count_reps(e['gravityX']), count_reps(e['gravityY']), count_reps(e['gravityZ'])])
    
    for e in (squat):
        squat_out.append([count_reps(e['gravityX']), count_reps(e['gravityY']), count_reps(e['gravityZ'])])
    
    for e in (deadlift):
        deadlift_out.append([count_reps(e['gravityX']), count_reps(e['gravityY']), count_reps(e['gravityZ'])])
    time_f = time.time() - start_time
    return (time_f/(len(squat) + len(bench) + len(deadlift)))


bench_preproc = [(e[['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy() for e in bench ]
squat_preproc = [(e[['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy() for e in squat ]
deadlift_preproc = [(e[['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy() for e in deadlift ]
def m2():
    start_time = time.time()
    for e in (bench_preproc):
        #tens = (e[['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy()
        tens = e 
        bench_out_2.append(count_reps_2(tens))
    
    for e in (squat_preproc):
        #tens = (e[['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy()
        tens = e 
        squat_out_2.append(count_reps_2(tens))
        
    for e in (deadlift_preproc):
        #tens = (e[['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy()
        tens = e 
        deadlift_out_2.append(count_reps_2(tens))
    
    time_f = time.time() - start_time
    return (time_f/(len(squat) + len(bench) + len(deadlift)))
    

In [8]:
n = 1000
m_1 = [m1()*1000 for i in tqdm(range(n))]
m_2 = [m2()*1000 for i in tqdm(range(n))]

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:01<00:00, 808.58it/s]


In [9]:
#import matplotlib.pyplot as plt 


#plt.hist(m_1)

In [10]:
#plt.hist(m_2)

In [11]:
import torch

In [12]:
class Rep_count(torch.nn.Module):
    def __init__(self):
        self.values = torch.Tensor([0])
        pass


    def __call__(self, tens):
        tens -= torch.mean(tens, axis=0)
        t = torch.heaviside(tens, self.values)
        b = t[1:] - t[:-1]
        b = b[b.any(dim=1)]
        b[b==-1] = 0
        return torch.sum(b, dim=0)

model = Rep_count()

In [13]:
torch.Tensor(bench_preproc[-1])

tensor([[0.0267, 0.1017, 0.0178],
        [0.0265, 0.1015, 0.0169],
        [0.0263, 0.1011, 0.0161],
        ...,
        [0.0339, 0.1202, 0.0083],
        [0.0349, 0.1206, 0.0160],
        [0.0361, 0.1211, 0.0237]])

In [14]:
[model(torch.Tensor(e)) for e in bench_preproc]

[tensor([ 4., 19., 21.]),
 tensor([0., 6., 3.]),
 tensor([3., 9., 1.]),
 tensor([0., 7., 3.]),
 tensor([ 4., 19., 21.]),
 tensor([20., 22., 39.]),
 tensor([28., 20., 21.]),
 tensor([ 4., 13., 17.]),
 tensor([ 3., 26., 20.]),
 tensor([1., 8., 7.]),
 tensor([ 1., 24., 21.]),
 tensor([3., 5., 7.]),
 tensor([14., 15., 15.]),
 tensor([ 3., 10.,  7.]),
 tensor([20., 22., 39.]),
 tensor([ 4., 13., 10.]),
 tensor([20., 22., 39.])]

In [15]:
bench_out

[[np.int64(4), np.int64(20), np.int64(22)],
 [np.int64(1), np.int64(6), np.int64(4)],
 [np.int64(3), np.int64(9), np.int64(1)],
 [np.int64(1), np.int64(6), np.int64(4)],
 [np.int64(4), np.int64(20), np.int64(22)],
 [np.int64(20), np.int64(22), np.int64(39)],
 [np.int64(29), np.int64(19), np.int64(22)],
 [np.int64(4), np.int64(13), np.int64(18)],
 [np.int64(3), np.int64(26), np.int64(20)],
 [np.int64(2), np.int64(8), np.int64(7)],
 [np.int64(1), np.int64(24), np.int64(22)],
 [np.int64(4), np.int64(5), np.int64(8)],
 [np.int64(15), np.int64(15), np.int64(16)],
 [np.int64(3), np.int64(10), np.int64(7)],
 [np.int64(20), np.int64(22), np.int64(39)],
 [np.int64(4), np.int64(13), np.int64(10)],
 [np.int64(20), np.int64(22), np.int64(39)],
 [np.int64(4), np.int64(20), np.int64(22)],
 [np.int64(1), np.int64(6), np.int64(4)],
 [np.int64(3), np.int64(9), np.int64(1)],
 [np.int64(1), np.int64(6), np.int64(4)],
 [np.int64(4), np.int64(20), np.int64(22)],
 [np.int64(20), np.int64(22), np.int64(39)],

In [16]:
dummy_input = torch.Tensor((bench[0][['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy())
model(dummy_input)

tensor([ 4., 19., 21.])

In [17]:

class Rep_count(torch.nn.Module):
    def __init__(self):
        super(Rep_count, self).__init__()  # Properly initialize the base class
        self.values = torch.Tensor([0])

    def heaviside_custom(self, x, values):
        ones = torch.ones_like(x)
        zeros = torch.zeros_like(x)
        return torch.where(x > 0, ones, torch.where(x < 0, zeros, values))


    def forward(self, tens):
        tens = tens - torch.mean(tens, axis=0)
        t = self.heaviside_custom(tens, self.values)
        b = t[1:] - t[:-1]
        b = b[b.any(dim=1)]
        b[b == -1] = 0
        return torch.sum(b, dim=0)

model = Rep_count()
dummy_input = torch.Tensor((bench[0][['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy())
print(model(dummy_input))

torch.onnx.export(
    model, 
    dummy_input, 
    "model.onnx",
    input_names=["input"], 
    output_names=["output"],
    dynamic_axes={
        "input": {0: "batch_size", 1: "sequence_length"},   
        "output": {0: "batch_size", 1: "sequence_length"}
    }
)


tensor([ 4., 19., 21.])


In [24]:
import onnx
from onnx_tf.backend import prepare

onnx_model = onnx.load("model.onnx")
tf_rep = prepare(onnx_model)


/opt/homebrew/Caskroom/miniconda/base/envs/new_env/lib/python3.9/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
/opt/homebrew/Caskroom/miniconda/base/envs/new_env/lib/python3.9/site-packages/tensorflow_addons/utils/ensure_tf_install.py:53: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.13.0 and strictly below 2.16.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.18.0 and is not supported. 
Some things might work, some things might not.
If you we

ModuleNotFoundError: No module named 'keras.src.engine'

In [23]:
!pip uninstall tensorflow-addons
~pip install tensorflow-addons-nightly


  Using cached tf_keras-2.19.0-py3-none-any.whl.metadata (1.8 kB)
INFO: pip is looking at multiple versions of tf-keras to determine which version is compatible with other requirements. This could take a while.
  Using cached tf_keras-2.18.0-py3-none-any.whl.metadata (1.6 kB)
Using cached tf_keras-2.18.0-py3-none-any.whl (1.7 MB)


In [4]:
import tensorflow as tf

class RepCount(tf.keras.Model):
    def __init__(self):
        super(RepCount, self).__init__()
        self.values = tf.constant([0], dtype=tf.float32)

    def heaviside_custom(self, x, values):
        ones = tf.ones_like(x)
        zeros = tf.zeros_like(x)
        return tf.where(x > 0, ones, tf.where(x < 0, zeros, values))

    def call(self, tens):
        tens = tens - tf.reduce_mean(tens, axis=0)
        t = self.heaviside_custom(tens, self.values)
        b = t[1:] - t[:-1]
        mask = tf.reduce_any(tf.not_equal(b, 0), axis=1)
        b = tf.boolean_mask(b, mask)
        b = tf.where(tf.equal(b, -1), tf.zeros_like(b), b)
        return tf.reduce_sum(b, axis=0)

# Example usage:
model = RepCount()
# Create a dummy input tensor (adjust shape as needed)
dummy_input = tf.constant((bench[0][['gravityX', 'gravityY', 'gravityZ']]).dropna().to_numpy())
output = model(dummy_input)
print("Output:", output)


Output: tf.Tensor([ 4. 19. 21.], shape=(3,), dtype=float32)
